---
- name: Install curl and git
  apt:
    name:
      - curl
      - git
- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: /home/isaac/.asdf
    version: v0.10.2
  become: true
  become_user: isaac
- name: Setup asdf plugins
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && asdf plugin add erlang
      && asdf plugin add elixir'
    executable: /bin/bash
  become: true
  become_user: isaac
- name: Copy erlang build dependencies
  copy:
    src: erlang-build-dependencies_1.0_all.deb
    dest: /tmp/erl.deb
- name: Install erlang build dependencies
  command: apt-get install /tmp/erl.deb
- name: Install erlang with asdf
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && asdf install erlang 25.2
      && asdf global erlang 25.2'
    executable: /bin/bash
  become: true
  become_user: isaac
- name: Install elixir with asdf
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && asdf install elixir 1.14.2-otp-25
      && asdf global elixir 1.14.2-otp-25'
    executable: /bin/bash
  become: true
  become_user: isaac
- name: Install hex and rebar3
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && mix local.hex --force
      && mix local.rebar --force'
    executable: /bin/bash
  become: true
  become_user: isaac
- name: Install livebook
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && mix escript.install --force hex livebook
      && asdf reshim elixir'
    executable: /bin/bash
  become: true
  become_user: isaac
- name: Install phoenix
  shell:
    cmd: 'source /home/isaac/.asdf/asdf.sh
      && mix archive.install --force hex phx_new'
    executable: /bin/bash
  become: true
  become_user: isaac
