---
- name: Install dbus-x11
  apt:
    name: dbus-x11
- name: Load dconf settings
  command:
    cmd: /usr/bin/dconf load /
    stdin: |
      [org/gnome/desktop/background]
      color-shading-type='solid'
      picture-options='zoom'
      picture-uri='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
      picture-uri-dark='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
      primary-color='#000000'
      secondary-color='#000000'

      [org/gnome/desktop/input-sources]
      per-window=false

      [org/gnome/desktop/interface]
      color-scheme='prefer-dark'
      font-hinting='slight'
      gtk-theme='Yaru-blue-dark'
      icon-theme='Yaru-blue'
      monospace-font-name='Source Code Variable 10.75'

      [org/gnome/desktop/media-handling]
      autorun-x-content-ignore=@as []
      autorun-x-content-open-folder=@as []
      autorun-x-content-start-app=['x-content/ostree-repository']

      [org/gnome/desktop/notifications]
      show-in-lock-screen=false

      [org/gnome/desktop/peripherals/touchpad]
      two-finger-scrolling-enabled=true

      [org/gnome/desktop/screensaver]
      color-shading-type='solid'
      lock-delay=uint32 0
      lock-enabled=false
      picture-options='zoom'
      picture-uri='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
      primary-color='#000000'
      secondary-color='#000000'

      [org/gnome/desktop/search-providers]
      sort-order=['org.gnome.Contacts.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Nautilus.desktop']

      [org/gnome/desktop/session]
      idle-delay=uint32 0

      [org/gnome/gedit/preferences/editor]
      scheme='Yaru-dark'

      [org/gnome/settings-daemon/plugins/power]
      sleep-inactive-ac-timeout=3600
      sleep-inactive-ac-type='nothing'

      [org/gnome/shell]
      favorite-apps=['firefox_firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'code_code.desktop']

      [org/gnome/shell/extensions/dash-to-dock]
      dock-fixed=false
      dock-position='BOTTOM'
      extend-height=false

      [org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
      background-color='rgb(0,0,0)'
      foreground-color='rgb(255,255,255)'
      palette=['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(0,0,238)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(229,229,229)', 'rgb(127,127,127)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(92,92,255)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']
      use-theme-colors=false
  become: true
  become_user: isaac
