---
- name: Install git and zsh
  apt:
    name:
      - git
      - zsh
- name: Get oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
- name: Install oh-my-zsh
  command:
    argv:
      - /bin/sh
      - /tmp/install-oh-my-zsh.sh
      - --unattended
  become: true
  become_user: isaac
- name: Remove oh-my-zsh installer
  file:
    path: /tmp/install-oh-my-zsh.sh
    state: absent
- name: Set zsh as default shell
  user:
    name: isaac
    shell: /bin/zsh
- name: Install custom theme (1/2)
  copy:
    src: isaac.zsh-theme
    dest: /home/isaac/.oh-my-zsh/custom/themes/isaac.zsh-theme
  become: true
  become_user: isaac
- name: Install custom theme (2/2)
  lineinfile:
    path: /home/isaac/.zshrc
    regexp: ^ZSH_THEME=
    line: ZSH_THEME="isaac"
  become: true
  become_user: isaac
- name: Install path plugin (1/3)
  file:
    path: /home/isaac/.oh-my-zsh/custom/plugins/path
    state: directory
  become: true
  become_user: isaac
- name: Install path plugin (2/3)
  copy:
    src: path.plugin.zsh
    dest: /home/isaac/.oh-my-zsh/custom/plugins/path/path.plugin.zsh
  become: true
  become_user: isaac
- name: Install path plugin (3/3)
  lineinfile:
    path: /home/isaac/.zshrc
    regexp: ^plugins=
    line: plugins=(command-not-found git path)
  become: true
  become_user: isaac
